# mkdocs.yml
site_name: Quecital Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Quecital Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md